site_name: "CSS Tutorials"
site_url: https://cssedu.2.rahtiapp.fi
theme:
  name: material
  custom_dir: extras
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-variant
        name: Switch to Light mode
      accent: csc-orange
      primary: custom

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark mode
      accent: csc-orange
      primary: custom

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to System default mode
      accent: csc-orange
      primary: custom
  logo: csc_logo.svg
  icon:
    admonition:
      css-tutorial: material/lightning-bolt
  favicon: csc_logo.svg
extra_css:
  - extra.css
plugins:
  - tags:
      tags_file: tags.md
  - search
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
nav:
  - 'Start': 'index.md'
  - 'Authentication and authorization infrastucture':
    - Haka: 'haka/index.md'
    - 'My CSC': 'mycsc/index.md'
  - 'Remote desktop and environment for sensitive data':
    - 'SD Desktop': 'sd-desktop/index.md'
  - 'National HPC/HPA/AI':
    - 'Docs CSC': 'docs-csc.md'
    - 'Puhti': 'puhti/index.md'
  - 'Community cloud':
    - cPouta: 'cpouta/index.md'
  - 'Virtual private cloud':
    - ePouta: 'epouta.md'
  - 'Database as a service':
    - Pukki: 'pukki/index.md'
  - 'Container cloud':
    - Rahti: 'rahti/index.md'
  - 'Easy data analytics':
    - 'CSC Noppe': 'noppe/index.md'
  - 'High-capacity storage':
    - Allas: 'allas/index.md'
  - 'Sensitive data storage':
    - 'SD Connect': 'sd-connect/index.md'
  - 'Articles sorted by tags': 'tags.md'
